services:
  db:
    image: postgres:13
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_PASSWORD: dev-password
      POSTGRES_USER: playfulbot_backend
  nginx:
    build: ./nginx
    extra_hosts:
      - "backend:host-gateway"
      - "frontend:host-gateway"
    ports:
      - "127.0.0.1:80:80"
      - "127.0.0.1:443:443"
    volumes:
      - ./ssl:/playfulbot/ssl