/**
 * Types extending the ones generated by Graphql Code Generator
 */

import * as gqlTypes from './graphql-generated';

import { GameState } from './gameState';

export * from './graphql-generated';

export interface Game<GS extends GameState> extends gqlTypes.Game {
  gameState: GS;
}

export interface GameSchedule<GS extends GameState> extends gqlTypes.GameSchedule {
  game?: gqlTypes.Maybe<Game<GS>>;
}

export type LiveGame<GS extends GameState> = Game<GS> | gqlTypes.GamePatch;
